import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const here = new URL('./', import.meta.url);
const qrVendor = await readFile(new URL('vendor/qrcode.js', here), 'utf8');
const qrRuntime = (await readFile(new URL('src/qr-runtime.mjs', here), 'utf8')).replace(/^export /gm, '');
await writeFile(new URL('src/qr-assets.mjs', here), `// Generated by build.mjs; QR encoder carries its MIT license in vendor/LICENSE.qrcode.\nexport const QR_VENDOR_SOURCE = ${JSON.stringify(qrVendor)};\nexport const QR_RUNTIME_SOURCE = ${JSON.stringify(qrRuntime)};\n`);
const parts = await Promise.all(['core', 'shortcut', 'qr-assets', 'qr-html', 'login-dialog', 'plugin'].map(async name =>
    (await readFile(new URL(`src/${name}.mjs`, here), 'utf8'))
        .replace(/^import .* from '\.\/.*';\n/gm, '').replace(/^export /gm, '')));
const bundle = `(() => {\n'use strict';\n${parts.join('\n')}\nreturn createPlugin(vendetta);\n})()\n`;
await writeFile(new URL('index.js', here), bundle);
const manifest = JSON.parse(await readFile(new URL('manifest.base.json', here), 'utf8'));
manifest.hash = createHash('sha256').update(bundle).digest('hex');
await writeFile(new URL('manifest.json', here), JSON.stringify(manifest, null, 2) + '\n');
console.log(`Built ${manifest.name} ${manifest.version}: ${Buffer.byteLength(bundle)} bytes`);
