import { build } from "esbuild";
import { fileURLToPath } from "node:url";

process.chdir(fileURLToPath(new URL(".", import.meta.url)));
await build({
    entryPoints: ["src/gif.js"],
    outfile: "saveAsSticker/gif.js",
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "inline",
    banner: { js: "// Generated by npm run build. See src/gif.js and THIRD_PARTY_LICENSES.txt.\n// SaveAsSticker GIF converter; GPL-3.0-or-later. Bundled libraries: MIT." }
});
